from .hooks import (
    HookContext,
    execute_hooks,
    execute_hooks_background,
    register_dream_hook,
    register_hook,
    register_memory_extraction_hook,
    register_metrics_hook,
    register_session_memory_hook,
    unregister_hook,
)
from .compaction import CompactionEngine, needs_compaction, estimate_tokens
from .away_summary import generate_away_summary
from .magic_docs import MagicDocsService, detect_magic_doc
from .agent_summary import AgentSummarizer
from .hooks_http import (
    exec_http_hook,
    register_http_webhook_hook,
    register_env_webhook,
)
from .analytics import (
    attach_analytics_sink,
    log_event,
    log_event_async,
    log_threat_event,
    log_tool_call,
    strip_proto_fields,
    AnalyticsSink,
    AnalyticsStr,
)
from .session_storage import (
    SessionMetadata,
    record_transcript,
    record_message,
    load_transcript,
    load_full_transcript,
    save_metadata,
    load_metadata,
    list_sessions,
    delete_session,
    get_transcript_path,
    get_metadata_path,
    new_session_id,
)
from .conversation_recovery import (
    RecoveryResult,
    load_conversation_for_resume,
    load_most_recent_session,
    deserialize_messages,
    filter_unresolved_tool_uses,
    detect_interruption,
)

__all__ = [
    "HookContext",
    "execute_hooks",
    "execute_hooks_background",
    "register_dream_hook",
    "register_hook",
    "register_memory_extraction_hook",
    "register_metrics_hook",
    "register_session_memory_hook",
    "unregister_hook",
    "CompactionEngine",
    "needs_compaction",
    "estimate_tokens",
    "generate_away_summary",
    "MagicDocsService",
    "detect_magic_doc",
    "AgentSummarizer",
    "exec_http_hook",
    "register_http_webhook_hook",
    "register_env_webhook",
    "attach_analytics_sink",
    "log_event",
    "log_event_async",
    "log_threat_event",
    "log_tool_call",
    "strip_proto_fields",
    "AnalyticsSink",
    "AnalyticsStr",
    "SessionMetadata",
    "record_transcript",
    "record_message",
    "load_transcript",
    "load_full_transcript",
    "save_metadata",
    "load_metadata",
    "list_sessions",
    "delete_session",
    "get_transcript_path",
    "get_metadata_path",
    "new_session_id",
    "RecoveryResult",
    "load_conversation_for_resume",
    "load_most_recent_session",
    "deserialize_messages",
    "filter_unresolved_tool_uses",
    "detect_interruption",
]
